# Generated by Django 4.0.3 on 2022-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_user_is_patient_user_is_physician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_physician',
            new_name='is_teamlead',
        ),
    ]
