# Generated by Django 4.0.3 on 2022-04-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_physician'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='team',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='patients.userprofile'),
            preserve_default=False,
        ),
    ]
