# Generated by Django 4.0.3 on 2022-04-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_department_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physicians', to='patients.department'),
        ),
    ]
